# Spring AI foundation
spring:
  ai:
    model:
      chat: google-genai
      embedding:
        text: google-genai

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.1-flash-lite
        embedding:
          api-key: ${GEMINI_API_KEY}
          text:
            model: gemini-embedding-001
            dimensions: 1536

    vectorstore:
      pgvector:
        id-type: TEXT
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: ${AI_PGVECTOR_INITIALIZE_SCHEMA:false}
        remove-existing-vector-store-table: false
        schema-name: public
        table-name: vector_store
